### ISSUE TITLE
npm install shows many vulnerabilities

### ISSUE THREAD

**Issue by hamoid** [llorenspujol/parcel-pixijs-quickstarter#11]
`found 56366 vulnerabilities (41508 low, 15 moderate, 14843 high)`

Are there plans to fix these? Cheers!

**Comment by llorenspujol** [comment]
Well seen, I didn't see it on the last update. They are fixed now, except one high vulnerability from `node-forge` that `parcel-bundler` depends on, so for now we can't not avoid it. We will have to wait until the release of parcel v2:)

Cheers!
